minesweeper: runner.o function.o
	gcc runner.o function.o -o minesweeper
runner.o: runner.c minesweeper.h
	gcc runner.c -c
function.0: function.c minesweeper.h
	gcc function.c -c
clean:
	rm* .o Minesweeper

